### ISSUE TITLE
Program to find Area of Geometric Shapes C++/Java/Python ( HacktoberFest 2021 )

### ISSUE THREAD

**Issue by viveeeeeek** [ajinkyabodke/Learning_Resources#18]

**Comment by viveeeeeek** [comment]
We are still creating issues. Once we are done with that I'll start assigning it, so don't worry. 
Thank you for your patience.

**Comment by tausiq2003** [comment]
I will do please assign

**Comment by yashneet-kalra** [comment]
Hi @viveeeeeek ! I have added this program in C Language in PR #45 . Please review and merge.

**Comment by DivasGupta7** [comment]
I want to work on this in c++, please assign me @viveeeeeek

**Comment by viveeeeeek** [comment]
@DivasGupta7 I've assigned this to you

**Comment by tausiq2003** [comment]
this may be excluded because you have closed this issue
