### ISSUE TITLE
Program to find Fibonacci Series C++/Java/Python ( HacktoberFest 2021 )

### ISSUE THREAD

**Issue by viveeeeeek** [ajinkyabodke/Learning_Resources#19]

**Comment by shaurya5** [comment]
I'll do this

**Comment by ajay-makvana** [comment]
I want to work on this issue

**Comment by viveeeeeek** [comment]
We are still creating issues. Once we are done with that I'll start assigning it, so don't worry. 
Thank you for your patience.

**Comment by ajinkyabodke** [comment]
i have assigned it to both of you @shaurya5 @ajay-makvana ,please submit it at the earliest,make sure to star the repo first

**Comment by shaurya5** [comment]
> i have assigned it to both of you @shaurya5 @ajay-makvana ,please submit it at the earliest,make sure to star the repo first
> 

i have sent a PR already

**Comment by Diptadip** [comment]
Solved this issue, check out PR #26

**Comment by aark06** [comment]
I'd like to work on this issue in java, please assign it to me.

**Comment by Meghwantsingh** [comment]
Hello, I'm new to this can i also solve this problem  in C++.

**Comment by diego-rapoport** [comment]
I'd like to work on this in python, if it still available! I'm also new do hacktoberfest.
