### ISSUE TITLE
We are still creating issues. Once we are done with that I'll start assigning it, so don't worry.

### ISSUE THREAD

**Issue by ajinkyabodke** [ajinkyabodke/Learning_Resources#22]
We are still creating issues. Once we are done with that I'll start assigning it, so don't worry.
Issues would be assigned from **tomorrow 12:00 IST and PRs would be mereged by 18:00 IST.**
Thank you for your patience.
You can aslo try contributing to other repos on github like `https://github.com/viveeeeeek/1stHacktoberfest`

**Comment by sohilkhanduja** [comment]
Hey @ajinkyabodke You should keep closing issues and you should not accept more than 1 pull request in a day. Otherwise your repository will be marked as sp and will be excluded in Hacktoberfest.
