### ISSUE TITLE
Leetcode: Trapping Rainwater problem

### ISSUE THREAD

**Issue by binayshaw7777** [ajinkyabodke/Learning_Resources#94]
I would like to submit the code for https://leetcode.com/problems/trapping-rain-water/ with multiple approaches in Java.

**Comment by PurtiMishra** [comment]
Hey, I would like to contribute the best possible solutions for it. Please assign this task to me

**Comment by yashasvi-sharma** [comment]
I would like to bestow the best solution for this. Please assign this to me @binayshaw7777

**Comment by Sakshi2002-Sinha** [comment]
Hello, Please assign me this issue.
Thanks in advance :)
